apiVersion: v1
kind: Service
metadata:
  name: demo-server-service
spec:
  type: NodePort # NodePort / LoadBalancer / Ingress
  ports:
  - port: 80
    protocol: TCP
    targetPort: server-port
  selector:
    app: demo-server